/**
 * communityLevels.js — Auto-generated by scripts/sync-community.js
 * Fallback data for GitHub Pages (no API) or offline use.
 * Run `node scripts/sync-community.js` to update.
 */
export const COMMUNITY_LEVELS = [];
