import { ctx, drawPixelCircle } from '../core/render.js';
import { W, H, COLORS, SHIELD_RADIUS } from '../core/constants.js';
import { game, player } from '../core/state.js';
import { spawnParticles } from '../systems/particles.js';
import { damagePlayer } from '../systems/damage.js';
import { checkBulletPrismCollisions } from '../objects/prism.js';
import { checkBulletPortalCollision } from '../objects/portals.js';
import { explodeBarrel } from '../objects/barrels.js';

export function fireBullet(){if(game.shots<=0)return;game.shots--;const speed=6,gx=player.x+Math.cos(game.gunAngle)*player.gunLength,gy=player.y+Math.sin(game.gunAngle)*player.gunLength,ip=game.piercingCount>0;if(ip)game.piercingCount--;game.bullets.push({x:gx,y:gy,vx:Math.cos(game.gunAngle)*speed,vy:Math.sin(game.gunAngle)*speed,bounces:0,maxBounces:game.maxBounces,life:300,trail:[],piercing:ip,piercingUsed:false,fromPrism:false,lastPortal:null});}

export function updateBullets(dt){for(let i=game.bullets.length-1;i>=0;i--){const b=game.bullets[i];b.trail.push({x:b.x,y:b.y});if(b.trail.length>12)b.trail.shift();b.x+=b.vx;b.y+=b.vy;b.life--;if(checkBulletPrismCollisions(i))continue;checkBulletPortalCollision(b);if(b.x<=6||b.x>=W-6){if(b.piercing&&!b.piercingUsed){b.piercingUsed=true;b.x=b.x<=6?W-8:8;spawnParticles(b.x,b.y,'#ffaaff',6);}else{b.vx*=-1;b.x=b.x<=6?6:W-6;b.bounces++;spawnParticles(b.x,b.y,COLORS.laserGlow,4);}}if(b.y<=6||b.y>=H-6){if(b.piercing&&!b.piercingUsed){b.piercingUsed=true;b.y=b.y<=6?H-8:8;spawnParticles(b.x,b.y,'#ffaaff',6);}else{b.vy*=-1;b.y=b.y<=6?6:H-6;b.bounces++;spawnParticles(b.x,b.y,COLORS.laserGlow,4);}}for(let j=game.enemies.length-1;j>=0;j--){const e=game.enemies[j];if(Math.hypot(b.x-e.x,b.y-e.y)<e.size+4){e.hp-=game.bulletDamage;e.flashTimer=0.15;spawnParticles(e.x,e.y,COLORS.enemy,8);if(e.hp<=0){spawnParticles(e.x,e.y,'#ffcc44',16);if(game.playerHp<game.playerMaxHp&&Math.random()<0.25){game.apples.push({x:e.x,y:e.y,size:8,bobPhase:0});}game.enemies.splice(j,1);game.killedEnemies++;if(e.type==='tank'){game.shots+=5;game.score+=200*game.level;}else{game.shots+=3;game.score+=100*game.level;}game.screenShake=0.2;}game.bullets.splice(i,1);break;}}if(!game.bullets[i])continue;for(let j=game.apples.length-1;j>=0;j--){const a=game.apples[j];if(Math.hypot(b.x-a.x,b.y-a.y)<a.size+4){spawnParticles(a.x,a.y,'#ff4444',12);spawnParticles(a.x,a.y,'#44dd22',6);game.apples.splice(j,1);if(game.playerHp<game.playerMaxHp){game.playerHp++;}game.score+=50;game.screenShake=0.1;game.bullets.splice(i,1);break;}}if(!game.bullets[i])continue;for(let j=game.barrels.length-1;j>=0;j--){const barrel=game.barrels[j];if(barrel.exploded)continue;if(Math.hypot(b.x-barrel.x,b.y-barrel.y)<barrel.size+4){explodeBarrel(barrel);game.bullets.splice(i,1);break;}}if(!game.bullets[i])continue;if(b.bounces>0&&game.shieldActive){const dist=Math.hypot(b.x-player.x,b.y-player.y);if(dist<SHIELD_RADIUS&&dist>0){const nx=(b.x-player.x)/dist,ny=(b.y-player.y)/dist,dot=b.vx*nx+b.vy*ny;b.vx-=2*dot*nx;b.vy-=2*dot*ny;b.x=player.x+nx*(SHIELD_RADIUS+2);b.y=player.y+ny*(SHIELD_RADIUS+2);b.bounces++;game.shieldEnergy=Math.max(0,game.shieldEnergy-8);spawnParticles(b.x,b.y,COLORS.shield,6);if(game.shieldEnergy<=0){game.shieldActive=false;game.shieldCooldown=true;}continue;}}if((b.bounces>0||b.fromPrism)&&player.invincibleTimer<=0){if(Math.hypot(b.x-player.x,b.y-player.y)<player.size+3){game.bullets.splice(i,1);if(damagePlayer('\u88AB\u81EA\u5DF1\u7684\u6FC0\u5149\u51FB\u6740\u4E86!'))return;continue;}}if(b.bounces>b.maxBounces||b.life<=0){spawnParticles(b.x,b.y,COLORS.bullet,3);game.bullets.splice(i,1);}}}

export function drawBullet(b){const ip=b.piercing&&!b.piercingUsed;for(let i=0;i<b.trail.length;i++){const a=i/b.trail.length,s=2+a*2;ctx.fillStyle=ip?`rgba(255,170,255,${a*0.5})`:`rgba(0,255,200,${a*0.4})`;ctx.fillRect(Math.floor(b.trail[i].x-s/2),Math.floor(b.trail[i].y-s/2),s,s);}ctx.shadowColor=ip?'#ffaaff':COLORS.laserGlow;ctx.shadowBlur=12;drawPixelCircle(b.x,b.y,4,ip?'#ff88ff':COLORS.bullet);drawPixelCircle(b.x,b.y,2,'#ffffff');ctx.shadowBlur=0;}
